CREATE TABLE CHARACTER (
    NAME    CHAR(30),
    INTELLIGENCE    INT    CHECK(INTELLIGENCE>=0),
    STRENGTH    INT    CHECK(STRENGTH>=0),
    DEXTERITY    INT    CHECK(DEXTERITY>=0),
    WISDOM    INT    CHECK(WISDOM>=0),
    CONSTITUTION    INT    CHECK(CONSTITUTION>=0),
    CHARISMA    INT    CHECK(CHARISMA>=0),
    RACE_NAME     CHAR(30),
    PRIMARY KEY (NAME)
    FOREIGN KEY (RACE_NAME) REFERENCES RACE(NAME)
    );
    
CREATE TABLE INVENTORY (
    ITEMS     CHAR(30),
    CHARACTER_NAME     CHAR(30),
    FOREIGN KEY (CHARACTER_NAME) REFERENCES CHARACTER(NAME)
        ON DELETE CASCADE
    );
    
CREATE TABLE CAMPAIGN (
    NAME     CHAR(30),
    REGION    CHAR(30)    NOT NULL,
    NPCS    INT    CHECK(NPCS>=0),
    NUM_PLAYERS    INT    NOT NULL    CHECK(NUM_PLAYERS>=0),
    CHARACTER_NAME    CHAR(30)    NOT NULL,
    PRIMARY KEY (NAME),
    FOREIGN KEY (CHARACTER_NAME) REFERENCES CHARACTER(NAME)
    );
    
CREATE TABLE CLASS (
    NAME    CHAR(30),
    HIT_DIE    INT    NOT NULL    CHECK(HIT_DIE>=0),
    SAVING_THROWS    CHAR(30)    NOT NULL,
    PROFICIENCIES    CHAR(100)    NOT NULL,
    PROFICIENCY_BONUS    INT    CHECK(PROFICIENCY_BONUS>=0),
    CLASS_FEATS    CHAR(100),
    ABILITY_SCORE_INCREASE    INT    CHECK(ABILITY_SCORE_INCREASE>=0),
    PRIMARY KEY (NAME)
    );

CREATE TABLE FEATS (
    NAME    CHAR(30),
    PREREQUISITES    CHAR(200),
    DESCRIPTION    CHAR(200)    NOT NULL,
    PRIMARY KEY (NAME)
    );
    
CREATE TABLE RACE (
    NAME    CHAR(30),
    RACIAL_FEATS    CHAR(100),
    LANGUAGES    CHAR(30)    NOT NULL,
    PROFICIENCIES    CHAR(100)    NOT NULL,
    ABILITY_SCORE_INCREASE    INT    CHECK(ABILITY_SCORE_INCREASE>=0),
    SPEED    INT    NOT NULL    CHECK(SPEED>=0),
    SIZE    INT    NOT NULL    CHECK(SIZE>=0),
    PRIMARY KEY (NAME)
    );

CREATE TABLE SUB_RACE (
    NAME    CHAR(30),
    PROFICIENCIES    CHAR(100)    NOT NULL,
    ABILITY_SCORE_INCREASE    INT    CHECK(ABILITY_SCORE_INCREASE>=0),
    RACIAL_FEATS    CHAR(100),
    PRIMARY_RACE_NAME    CHAR(30)    NOT NULL,
    FOREIGN KEY (PRIMARY_RACE_NAME) REFERENCES RACE(NAME)
    );