CREATE TABLE CHARACTER (
    NAME    CHAR(30),
    INTELLIGENCE    INT,
    STRENGTH    INT,
    DEXTERITY    INT,
    WISDOM    INT,
    CONSTITUTION    INT,
    CHARISMA    INT,
    RACE_NAME     CHAR(30),
    PRIMARY KEY (NAME)
    FOREIGN KEY (RACE_NAME)
    );
    
CREATE TABLE INVENTORY (
    ITEMS     CHAR(30),
    CHARACTER_NAME     CHAR(30),
    FOREIGN KEY (CHARACTER_NAME) REFERENCES CHARACTER(NAME)
    );
    
CREATE TABLE CAMPAIGN (
    NAME     CHAR(30),
    REGION    CHAR(30)    NOT NULL,
    NPCS    INT,
    NUM_PLAYERS    INT    NOT NULL,
    CHARACTER_NAME    CHAR(30)    NOT NULL,
    PRIMARY KEY (NAME),
    FOREIGN KEY (CHARACTER_NAME) REFERENCES CHARACTER(NAME)
    );
    
CREATE TABLE CLASS (
    NAME    CHAR(30),
    HIT_DIE    INT    NOT NULL,
    SAVING_THROWS    CHAR(30)    NOT NULL,
    PROFICIENCIES    CHAR(100)    NOT NULL,
    PROFICIENCY_BONUS    INT,
    CLASS_FEATS    CHAR(100),
    ABILITY_SCORE_INCREASE    INT,
    PRIMARY KEY (NAME)
    );

CREATE TABLE HAS (
    CLASS_NAME    CHAR(30),
    CHARACTER_NAME    CHAR(30),
    FOREIGN KEY (CLASS_NAME) REFERENCES CLASS(NAME),
    FOREIGN KEY (CHARACTER_NAME) REFERENCES CHARACTER(NAME)
    );

CREATE TABLE FEATS (
    NAME    CHAR(30),
    PREREQUISITES    CHAR(200),
    DESCRIPTION    CHAR(200)    NOT NULL,
    PRIMARY KEY (NAME)
    );

CREATE TABLE POSSESSES (
    CHARACTER_NAME    CHAR(30)    NOT NULL,
    FEAT_NAME    CHAR(30)    NOT NULL,
    FOREIGN KEY (CHARACTER_NAME) REFERENCES CHARACTER(NAME),
    FOREIGN KEY (FEAT_NAME) REFERENCES FEATS(NAME)
    );
    
CREATE TABLE RACE (
    NAME    CHAR(30),
    RACIAL_FEATS    CHAR(100),
    LANGUAGES    CHAR(30)    NOT NULL,
    PROFICIENCIES    CHAR(100)    NOT NULL,
    ABILITY_SCORE_INCREASE    INT,
    SPEED    INT    NOT NULL,
    SIZE    INT    NOT NULL,
    PRIMARY KEY (NAME)
    );

CREATE TABLE SUB_RACE (
    NAME    CHAR(30),
    PROFICIENCIES    CHAR(100)    NOT NULL,
    ABILITY_SCORE_INCREASE    INT,
    RACIAL_FEATS    CHAR(100),
    PRIMARY_RACE_NAME    CHAR(30)    NOT NULL,
    FOREIGN KEY (PRIMARY_RACE_NAME) REFERENCES RACE(NAME)
    );